/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "akamai_edge_dns_zone_management_api/types";

export type GetRequest = {
  requestId: string;
  accountSwitchKey?: string;
};

export type CreateRequest = {
  accountSwitchKey?: string;
  bypassSafetyChecks?: boolean;
  data: types.PostZonesDeleteRequestsBody;
};
