/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "akamai_edge_dns_zone_management_api/types";

export type ListRequest = {
  accountSwitchKey?: string;
  contractIds?: string;
  page?: number;
  pageSize?: number;
  search?: string;
  showAll?: boolean;
  sortBy?: string;
  subzoneGrant?: boolean;
  types?: string;
};

export type GetRequest = {
  zone: string;
  accountSwitchKey?: string;
};

export type CreateRequest = {
  contractId: string;
  gid: number;
  accountSwitchKey?: string;
  data: types.PostZonesBody;
};

export type PutRequest = {
  zone: string;
  skipSignAndServeSafetyCheck: boolean;
  accountSwitchKey?: string;
  data: types.PutZonesZoneBody;
};
