/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "akamai_edge_dns_zone_management_api/core";
import * as requests from "akamai_edge_dns_zone_management_api/resources/changelists/submit/request-types";
import qs from "qs";

export class SubmitClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * Applies all of the changes in this change list to the current zone. This operation fails if the change list has become stale.
   */
  create(
    request: requests.CreateRequest,
    opts?: RequestOptions,
  ): ApiPromise<null> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "post",
      path: `/changelists/${request.zone}/submit`,
      query: [
        qs.stringify({
          skipSignAndServeSafetyCheck: request.skipSignAndServeSafetyCheck,
        }),
        qs.stringify({ accountSwitchKey: request.accountSwitchKey }),
        qs.stringify({ comment: request.comment }),
      ],
      responseType: "json",
      opts,
    });
  }
}
