/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "akamai_edge_dns_zone_management_api/core";
import * as requests from "akamai_edge_dns_zone_management_api/resources/zones/contract/request-types";
import * as types from "akamai_edge_dns_zone_management_api/types";
import qs from "qs";

export class ContractClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * Show data about the contract to which this zone belongs.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetZonesZoneContractResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/zones/${request.zone}/contract`,
      query: [
        qs.stringify({ gid: request.gid }),
        qs.stringify({ accountSwitchKey: request.accountSwitchKey }),
      ],
      responseType: "json",
      opts,
    });
  }
}
