/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  zone: string;
  accountSwitchKey?: string;
};

export type CreateRequest = {
  zone: string;
  accountSwitchKey?: string;
  data: string;
};
