/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  zone: string;
  accountSwitchKey?: string;
  page?: number;
  pageSize?: number;
  showAll?: boolean;
};

export type GetRequest = {
  zone: string;
  uuid: string;
  accountSwitchKey?: string;
};
