/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "akamai_edge_dns_zone_management_api/core";
import { DiffClient } from "akamai_edge_dns_zone_management_api/resources/zones/versions/diff";
import { RecordsetsClient } from "akamai_edge_dns_zone_management_api/resources/zones/versions/recordsets";
import { ZoneFileClient } from "akamai_edge_dns_zone_management_api/resources/zones/versions/zone-file";
import * as requests from "akamai_edge_dns_zone_management_api/resources/zones/versions/request-types";
import * as types from "akamai_edge_dns_zone_management_api/types";
import qs from "qs";

export class VersionsClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  diff: DiffClient;
  recordsets: RecordsetsClient;
  zoneFile: ZoneFileClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.diff = new DiffClient(this._client);
    this.recordsets = new RecordsetsClient(this._client);
    this.zoneFile = new ZoneFileClient(this._client);
  }

  // register api methods (keep comment for code generation)

  /**
   * Returns an image of the Zone from a previous version. Shows only zone settings, not record sets.
   */
  get(
    request: requests.GetRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetZonesZoneVersionsUuidResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/zones/${request.zone}/versions/${request.uuid}`,
      query: [qs.stringify({ accountSwitchKey: request.accountSwitchKey })],
      responseType: "json",
      opts,
    });
  }

  /**
   * Shows the settings for current and prior versions of this Zone, in reverse chronological order of modification. Many versions in this list may look very similar because a new version is created every time the zone's settings or record sets are changed. This operation is [paginated](https://techdocs.akamai.com/edge-dns/reference/use-pagination).
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetZonesZoneVersionsResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: `/zones/${request.zone}/versions`,
      query: [
        qs.stringify({ accountSwitchKey: request.accountSwitchKey }),
        qs.stringify({ page: request.page }),
        qs.stringify({ pageSize: request.pageSize }),
        qs.stringify({ showAll: request.showAll }),
      ],
      responseType: "json",
      opts,
    });
  }
}
