/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "akamai_edge_dns_zone_management_api/types";

export type CreateRequest = {
  accountSwitchKey?: string;
  data: types.PostZonesZoneTransferStatusBody;
};
