/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "akamai_edge_dns_zone_management_api/types";

export type GetRequest = {
  requestId: string;
  accountSwitchKey?: string;
};

export type CreateRequest = {
  contractId: string;
  gid: number;
  accountSwitchKey?: string;
  data: types.PostZonesCreateRequestsBody;
};
