/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "akamai_edge_dns_zone_management_api/core";
import * as requests from "akamai_edge_dns_zone_management_api/resources/data/groups/request-types";
import * as types from "akamai_edge_dns_zone_management_api/types";
import qs from "qs";

export class GroupsClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * Lists the groups accessible to the current user. Each Group object includes the list of contracts related to that group, as well as your permissions of `READ`, `WRITE`, `ADD`, or `DELETE` zone on that group.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetDataGroupsResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: "/data/groups",
      query: [
        qs.stringify({ gid: request.gid }),
        qs.stringify({ accountSwitchKey: request.accountSwitchKey }),
      ],
      responseType: "json",
      opts,
    });
  }
}
