/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "akamai_edge_dns_zone_management_api/core";
import * as requests from "akamai_edge_dns_zone_management_api/resources/data/recordset-types/request-types";
import * as types from "akamai_edge_dns_zone_management_api/types";
import qs from "qs";

export class RecordsetTypesClient extends CoreResourceClient {
  // register resources (keep comment for code generation)

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
  }

  // register api methods (keep comment for code generation)

  /**
   * Retrieves a list of record types you can add to the requested zone. Record types depend on both the zone type and the available contract features.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetDataRecordsetTypesResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: "/data/recordset-types",
      query: [
        qs.stringify({ zone: request.zone }),
        qs.stringify({ accountSwitchKey: request.accountSwitchKey }),
      ],
      responseType: "json",
      opts,
    });
  }
}
