/**
 * File Generated by Sideko (sideko.dev)
 */

export type GetDataEdgehostnamesResponseEdgeHostnamesItem = {
  edgeHostname: string;
  supportsZoneApexMapping: boolean;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string | boolean | any;
};
