/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type GetZonesZoneVersionsDiffResponseDiffsSettingsDiffsItem = {
  fieldName: string;
  fromValue?: boolean | number | Record<string, any> | string;
  operation: types.GetZonesZoneVersionsDiffResponseDiffsSettingsDiffsItemOperationEnum;
  toValue?: boolean | number | Record<string, any> | string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | undefined
    | (boolean | number | Record<string, any> | string)
    | types.GetZonesZoneVersionsDiffResponseDiffsSettingsDiffsItemOperationEnum
    | undefined
    | (boolean | number | Record<string, any> | string)
    | any;
};
