/**
 * File Generated by Sideko (sideko.dev)
 */

export enum GetZonesZoneContractResponseFeaturesItemEnum {
  AliasZones = "ALIAS_ZONES",
  DnssecSelfSign = "DNSSEC_SELF_SIGN",
  DnssecSignAndServe = "DNSSEC_SIGN_AND_SERVE",
  ForceDelete = "FORCE_DELETE",
  PrimaryZones = "PRIMARY_ZONES",
  SecondaryZones = "SECONDARY_ZONES",
  ZoneApexMapping = "ZONE_APEX_MAPPING",
  TldZones = "TLD_ZONES",
  SubzoneGrants = "SUBZONE_GRANTS",
}
