/**
 * File Generated by Sideko (sideko.dev)
 */

export enum GetZonesZoneKeyResponseAlgorithmEnum {
  HmacMd5SigAlgRegInt = "HMAC-MD5.SIG-ALG.REG.INT",
  HmacMd5 = "hmac-md5",
  HmacSha1 = "hmac-sha1",
  HmacSha224 = "hmac-sha224",
  HmacSha256 = "hmac-sha256",
  HmacSha384 = "hmac-sha384",
  HmacSha512 = "hmac-sha512",
}
