/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type GetZonesZoneContractResponse = {
  contractId: string;
  contractName: string;
  contractTypeName: string;
  features: types.GetZonesZoneContractResponseFeaturesItemEnum[];
  maximumZones: number;
  permissions: types.GetZonesZoneContractResponsePermissionsItemEnum[];
  zoneCount: number;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | string
    | types.GetZonesZoneContractResponseFeaturesItemEnum[]
    | number
    | types.GetZonesZoneContractResponsePermissionsItemEnum[]
    | number
    | any;
};
