/**
 * File Generated by Sideko (sideko.dev)
 */

export type GetChangelistsResponseChangeListsItem = {
  changeTag: string;
  lastModifiedDate: string;
  stale: boolean;
  zone: string;
  zoneVersionId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | boolean
    | string
    | string
    | any;
};
