/**
 * File Generated by Sideko (sideko.dev)
 */

export enum GetZonesZoneResponseSignAndServeAlgorithmEnum {
  RsaSha1 = "RSA_SHA1",
  RsaSha256 = "RSA_SHA256",
  RsaSha512 = "RSA_SHA512",
  EcdsaP256Sha256 = "ECDSA_P256_SHA256",
  EcdsaP384Sha384 = "ECDSA_P384_SHA384",
}
