/**
 * File Generated by Sideko (sideko.dev)
 */

export enum GetChangelistsZoneRecordsetsResponseRecordsetsItemStateEnum {
  Pristine = "PRISTINE",
  Added = "ADDED",
  Edited = "EDITED",
  Deleted = "DELETED",
}
