/**
 * File Generated by Sideko (sideko.dev)
 */

export type GetZonesZoneVersionsDiffResponseMetadata = {
  fromVersionId: string;
  fromVersionLastModifiedDate: string;
  toVersionId: string;
  toVersionLastModifiedDate: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string | string | string | string | any;
};
