/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type GetDataContractsResponseContractsItem = {
  contractId: string;
  contractName: string;
  contractTypeName: string;
  features: types.GetDataContractsResponseContractsItemFeaturesItemEnum[];
  maximumZones: number;
  permissions: types.GetDataContractsResponseContractsItemPermissionsItemEnum[];
  zoneCount: number;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | string
    | string
    | types.GetDataContractsResponseContractsItemFeaturesItemEnum[]
    | number
    | types.GetDataContractsResponseContractsItemPermissionsItemEnum[]
    | number
    | any;
};
