/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type PostZonesDnsSecStatusResponseDnsSecStatusesItem = {
  alerts: types.PostZonesDnsSecStatusResponseDnsSecStatusesItemAlertsItemEnum[];
  currentRecords: types.PostZonesDnsSecStatusResponseDnsSecStatusesItemCurrentRecords;
  newRecords?: types.PostZonesDnsSecStatusResponseDnsSecStatusesItemNewRecords;
  zone: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | types.PostZonesDnsSecStatusResponseDnsSecStatusesItemAlertsItemEnum[]
    | types.PostZonesDnsSecStatusResponseDnsSecStatusesItemCurrentRecords
    | undefined
    | types.PostZonesDnsSecStatusResponseDnsSecStatusesItemNewRecords
    | string
    | any;
};
