/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostZonesResponseActivationStateEnum {
  New = "NEW",
  PendingApproval = "PENDING_APPROVAL",
  Active = "ACTIVE",
  Obsolete = "OBSOLETE",
  Error = "ERROR",
  Locked = "LOCKED",
}
