/**
 * File Generated by Sideko (sideko.dev)
 */

export enum PostZonesDnsSecStatusResponseDnsSecStatusesItemAlertsItemEnum {
  IncompatibleAuthorities = "INCOMPATIBLE_AUTHORITIES",
  NonAkamaiAuthorities = "NON_AKAMAI_AUTHORITIES",
  ParentDsMissing = "PARENT_DS_MISSING",
  OldDnskey = "OLD_DNSKEY",
  WrongDnskey = "WRONG_DNSKEY",
}
