/**
 * File Generated by Sideko (sideko.dev)
 */

export type PostZonesDeleteRequestsResponse = {
  expirationDate: string;
  requestId: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]: string | string | any;
};
