/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type PostChangelistsZoneRecordsetsAddChangeBody = {
  name: string;
  op: types.PostChangelistsZoneRecordsetsAddChangeBodyOpEnum;
  rdata?: string[];
  ttl?: number;
  type: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | string
    | types.PostChangelistsZoneRecordsetsAddChangeBodyOpEnum
    | undefined
    | string[]
    | undefined
    | number
    | string
    | any;
};
