/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type PostZonesZoneTransferStatusResponseZonesItemMastersItemZoneTransferAgentsItemActionsItem =
  {
    actionType: types.PostZonesZoneTransferStatusResponseZonesItemMastersItemZoneTransferAgentsItemActionsItemActionTypeEnum;
    lastFailureTimestamp?: string;
    lastSuccessSerial?: number;
    lastSuccessTimestamp?: string;
    messages?: types.PostZonesZoneTransferStatusResponseZonesItemMastersItemZoneTransferAgentsItemActionsItemMessagesItem[];

    // Index types must also accommodate all defined properties if present (typescript limitation)
    // In reality all additional properties should only have type `any`
    // (there might be some duplication here)
    [additionalProperty: string]:
      | types.PostZonesZoneTransferStatusResponseZonesItemMastersItemZoneTransferAgentsItemActionsItemActionTypeEnum
      | undefined
      | string
      | undefined
      | number
      | undefined
      | string
      | undefined
      | types.PostZonesZoneTransferStatusResponseZonesItemMastersItemZoneTransferAgentsItemActionsItemMessagesItem[]
      | any;
  };
