/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type PostZonesCreateRequestsBodyZonesItem = {
  comment?: string;
  endCustomerId?: string;
  masters?: string[];
  signAndServe?: boolean;
  signAndServeAlgorithm?: types.PostZonesCreateRequestsBodyZonesItemSignAndServeAlgorithmEnum;
  target?: string;
  tsigKey?: types.PostZonesCreateRequestsBodyZonesItemTsigKey;
  type: types.PostZonesCreateRequestsBodyZonesItemTypeEnum;
  zone: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string[]
    | undefined
    | boolean
    | undefined
    | types.PostZonesCreateRequestsBodyZonesItemSignAndServeAlgorithmEnum
    | undefined
    | string
    | undefined
    | types.PostZonesCreateRequestsBodyZonesItemTsigKey
    | types.PostZonesCreateRequestsBodyZonesItemTypeEnum
    | string
    | any;
};
