/**
 * File Generated by Sideko (sideko.dev)
 */

import * as types from "akamai_edge_dns_zone_management_api/types";

export type PutZonesZoneBody = {
  comment?: string;
  contractId?: string;
  endCustomerId?: string;
  masters?: string[];
  signAndServe?: boolean;
  signAndServeAlgorithm?: types.PutZonesZoneBodySignAndServeAlgorithmEnum;
  subzoneGrants?: boolean;
  target?: string;
  tsigKey?: types.PutZonesZoneBodyTsigKey;
  type: types.PutZonesZoneBodyTypeEnum;
  zone: string;

  // Index types must also accommodate all defined properties if present (typescript limitation)
  // In reality all additional properties should only have type `any`
  // (there might be some duplication here)
  [additionalProperty: string]:
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string
    | undefined
    | string[]
    | undefined
    | boolean
    | undefined
    | types.PutZonesZoneBodySignAndServeAlgorithmEnum
    | undefined
    | boolean
    | undefined
    | string
    | undefined
    | types.PutZonesZoneBodyTsigKey
    | types.PutZonesZoneBodyTypeEnum
    | string
    | any;
};
