/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  zone: string;
  name: string;
  accountSwitchKey?: string;
};

export type GetRequest = {
  zone: string;
  name: string;
  typePath: string;
  accountSwitchKey?: string;
};
