/**
 * File Generated by Sideko (sideko.dev)
 */
import {
  CoreResourceClient,
  CoreClient,
  RequestOptions,
  ApiPromise,
} from "akamai_edge_dns_zone_management_api/core";
import { BulkUpdateClient } from "akamai_edge_dns_zone_management_api/resources/keys/bulk-update";
import { UsedByClient } from "akamai_edge_dns_zone_management_api/resources/keys/used-by";
import * as requests from "akamai_edge_dns_zone_management_api/resources/keys/request-types";
import * as types from "akamai_edge_dns_zone_management_api/types";
import qs from "qs";

export class KeysClient extends CoreResourceClient {
  // register resources (keep comment for code generation)
  bulkUpdate: BulkUpdateClient;
  usedBy: UsedByClient;

  constructor(client: CoreClient) {
    super(client);

    // init resources (keep comment for code generation)
    this.bulkUpdate = new BulkUpdateClient(this._client);
    this.usedBy = new UsedByClient(this._client);
  }

  // register api methods (keep comment for code generation)

  /**
   * Get a list of the TSIG keys used by zones that you are allowed to manage.
   */
  list(
    request: requests.ListRequest,
    opts?: RequestOptions,
  ): ApiPromise<types.GetKeysResponse> {
    // send request (keep comment for code generation)
    return this._client.makeRequest({
      method: "get",
      path: "/keys",
      query: [
        qs.stringify({ accountSwitchKey: request.accountSwitchKey }),
        qs.stringify({ contractIds: request.contractIds }),
        qs.stringify({ search: request.search }),
        qs.stringify({ sortBy: request.sortBy }),
      ],
      responseType: "json",
      opts,
    });
  }
}
