/**
 * File Generated by Sideko (sideko.dev)
 */

export type ListRequest = {
  zone: string;
  accountSwitchKey?: string;
  page?: number;
  pageSize?: number;
  search?: string;
  showAll?: boolean;
  sortBy?: string;
  types?: string;
};

export type CreateRequest = {
  zone: string;
  accountSwitchKey?: string;
  data: string;
};
