/**
 * File Generated by Sideko (sideko.dev)
 */
import * as types from "akamai_edge_dns_zone_management_api/types";

export type DeleteRequest = {
  zone: string;
  accountSwitchKey?: string;
};

export type ListRequest = {
  zone: string;
  accountSwitchKey?: string;
};

export type PutRequest = {
  zone: string;
  accountSwitchKey?: string;
  data: types.PutZonesZoneKeyBody;
};
