/**
 * File Generated by Sideko (sideko.dev)
 */
import { CoreClient } from "akamai_edge_dns_zone_management_api/core";
import { ChangelistsClient } from "akamai_edge_dns_zone_management_api/resources/changelists";
import { ZonesClient } from "akamai_edge_dns_zone_management_api/resources/zones";
import { DataClient } from "akamai_edge_dns_zone_management_api/resources/data";
import { KeysClient } from "akamai_edge_dns_zone_management_api/resources/keys";

export interface ClientOptions {
  hostname: string;
  timeout?: number;
}

export class Client {
  protected _client: CoreClient;
  // register resources (keep comment for code generation)
  changelists: ChangelistsClient;
  zones: ZonesClient;
  data: DataClient;
  keys: KeysClient;

  constructor(opts: ClientOptions) {
    const baseUrl = `https://{opts.hostname}/config-dns/v2`
    this._client = new CoreClient({ baseUrl, timeout: opts?.timeout });

    // register auth methods (keep comment for code generation)

    // init resources (keep comment for code generation)
    this.changelists = new ChangelistsClient(this._client);
    this.zones = new ZonesClient(this._client);
    this.data = new DataClient(this._client);
    this.keys = new KeysClient(this._client);
  }

  // register api methods (keep comment for code generation)
}
